import { Inter } from 'next/font/google';
import '../styles/globals.scss';

export const metadata = {
  title: 'Who Wants to Be a Millionaire',
  description: 'Generated by Next.js',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="page">{children}</body>
    </html>
  );
}
